-- MarketGuard 초기 스키마 (PostgreSQL). 운영 프로파일에서 Flyway가 적용한다.

CREATE TABLE price_snapshot (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code  VARCHAR(20)   NOT NULL,
    price       NUMERIC(19, 4) NOT NULL,
    captured_at TIMESTAMPTZ   NOT NULL
);
CREATE INDEX idx_snapshot_code_time ON price_snapshot (stock_code, captured_at);

CREATE TABLE anomaly_record (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code  VARCHAR(20)  NOT NULL,
    rule_type   VARCHAR(40)  NOT NULL,
    severity    VARCHAR(20)  NOT NULL,
    message     VARCHAR(500) NOT NULL,
    detected_at TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_anomaly_time ON anomaly_record (detected_at);

CREATE TABLE audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action     VARCHAR(60)  NOT NULL,
    detail     VARCHAR(500),
    outcome    VARCHAR(20)  NOT NULL,
    latency_ms BIGINT       NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_audit_at ON audit_log (created_at);
