-- Explainable anomaly evidence and reviewable surveillance cases.

CREATE TABLE surveillance_case (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code            VARCHAR(20)  NOT NULL,
    stock_name            VARCHAR(200) NOT NULL,
    title                 VARCHAR(120) NOT NULL,
    summary               VARCHAR(500) NOT NULL,
    score                 INTEGER      NOT NULL,
    attention_level       VARCHAR(20)  NOT NULL,
    score_explanation     VARCHAR(500) NOT NULL,
    status                VARCHAR(20)  NOT NULL,
    signal_count          INTEGER      NOT NULL,
    first_detected_at     TIMESTAMPTZ  NOT NULL,
    last_detected_at      TIMESTAMPTZ  NOT NULL,
    closed_at             TIMESTAMPTZ,
    updated_at            TIMESTAMPTZ  NOT NULL,
    reviewer              VARCHAR(120),
    closure_reason        VARCHAR(50),
    closure_detail        VARCHAR(500),
    context_tags          TEXT         NOT NULL DEFAULT '[]',
    version               BIGINT       NOT NULL DEFAULT 0,
    legacy_anomaly_id     BIGINT UNIQUE,
    CONSTRAINT chk_case_stock_code CHECK (stock_code ~ '^[0-9]{6}$'),
    CONSTRAINT chk_case_score CHECK (score BETWEEN 0 AND 100),
    CONSTRAINT chk_case_attention CHECK (attention_level IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_case_status CHECK (
        status IN ('NEW', 'REVIEWING', 'WATCHING', 'DISMISSED', 'ESCALATED', 'CLOSED')
    ),
    CONSTRAINT chk_case_signal_count CHECK (signal_count > 0),
    CONSTRAINT chk_case_time_order CHECK (last_detected_at >= first_detected_at),
    CONSTRAINT chk_case_context_tags_json CHECK (jsonb_typeof(context_tags::jsonb) = 'array'),
    CONSTRAINT chk_case_closure_reason CHECK (
        closure_reason IS NULL OR closure_reason IN (
            'MARKET_WIDE_MOVE', 'SECTOR_WIDE_MOVE', 'OPEN_OR_CLOSE_EFFECT',
            'EXPECTED_HIGH_VOLATILITY', 'PUBLIC_EVENT', 'DATA_ERROR',
            'TEMPORARY_ORDERBOOK_DISTORTION', 'NEEDS_FURTHER_REVIEW',
            'INACTIVITY', 'OTHER'
        )
    )
);
CREATE INDEX idx_case_last_detected ON surveillance_case (last_detected_at DESC, id DESC);
CREATE INDEX idx_case_stock_last ON surveillance_case (stock_code, last_detected_at DESC);
CREATE INDEX idx_case_status_score ON surveillance_case (status, score DESC);

CREATE TABLE case_note (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id    BIGINT        NOT NULL REFERENCES surveillance_case(id) ON DELETE CASCADE,
    author     VARCHAR(120)  NOT NULL,
    note       VARCHAR(2000) NOT NULL,
    created_at TIMESTAMPTZ   NOT NULL,
    CONSTRAINT chk_case_note_not_blank CHECK (length(trim(note)) > 0)
);
CREATE INDEX idx_case_note_case_time ON case_note (case_id, created_at);

CREATE TABLE case_status_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id     BIGINT       NOT NULL REFERENCES surveillance_case(id) ON DELETE CASCADE,
    from_status VARCHAR(20),
    to_status   VARCHAR(20)  NOT NULL,
    actor       VARCHAR(120) NOT NULL,
    reason      VARCHAR(50),
    detail      VARCHAR(500),
    changed_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT chk_case_history_to_status CHECK (
        to_status IN ('NEW', 'REVIEWING', 'WATCHING', 'DISMISSED', 'ESCALATED', 'CLOSED')
    )
);
CREATE INDEX idx_case_history_case_time ON case_status_history (case_id, changed_at);

CREATE TABLE case_group_lock (
    stock_code VARCHAR(20) PRIMARY KEY,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_case_lock_stock_code CHECK (stock_code ~ '^[0-9]{6}$')
);

ALTER TABLE anomaly_record
    ADD COLUMN stock_name VARCHAR(200),
    ADD COLUMN case_id BIGINT,
    ADD COLUMN title VARCHAR(120),
    ADD COLUMN summary VARCHAR(500),
    ADD COLUMN explanation VARCHAR(2000),
    ADD COLUMN observed_value NUMERIC(30, 8),
    ADD COLUMN baseline_value NUMERIC(30, 8),
    ADD COLUMN threshold_value NUMERIC(30, 8),
    ADD COLUMN deviation_ratio NUMERIC(30, 8),
    ADD COLUMN value_unit VARCHAR(30),
    ADD COLUMN lookback_description VARCHAR(200),
    ADD COLUMN direction VARCHAR(20),
    ADD COLUMN context_tags TEXT,
    ADD COLUMN recommended_checks TEXT,
    ADD COLUMN market_observed_at TIMESTAMPTZ,
    ADD COLUMN caution VARCHAR(500),
    ADD COLUMN measurements TEXT;

-- Preserve all existing records as one-signal legacy cases without inventing unavailable raw values.
INSERT INTO surveillance_case (
    stock_code, stock_name, title, summary, score, attention_level, score_explanation,
    status, signal_count, first_detected_at, last_detected_at, updated_at, context_tags,
    legacy_anomaly_id
)
SELECT stock_code,
       stock_code,
       CASE rule_type
           WHEN 'PRICE_LIMIT' THEN '가격제한폭 도달'
           WHEN 'PRICE_SPIKE' THEN '단기 가격 급변동'
           WHEN 'VOLUME_SURGE' THEN '거래량 급증'
           WHEN 'ORDERBOOK_IMBALANCE' THEN '호가 불균형'
           WHEN 'INVESTMENT_WARNING' THEN '투자경고 종목'
           ELSE '기존 탐지 신호'
       END,
       message,
       CASE rule_type
           WHEN 'PRICE_SPIKE' THEN 25
           WHEN 'VOLUME_SURGE' THEN 25
           WHEN 'ORDERBOOK_IMBALANCE' THEN 20
           WHEN 'PRICE_LIMIT' THEN 15
           WHEN 'INVESTMENT_WARNING' THEN 15
           ELSE 0
       END,
       'LOW',
       '구조화 근거 도입 전 단일 신호의 기본 기여점수',
       'NEW', 1, detected_at, detected_at, detected_at, '[]', id
FROM anomaly_record;

UPDATE anomaly_record anomaly
SET stock_name = anomaly.stock_code,
    case_id = surveillance.id,
    title = surveillance.title,
    summary = anomaly.message,
    explanation = '이 기록은 구조화된 근거 모델 도입 전에 생성되어 원시 비교값이 남아 있지 않습니다.',
    direction = 'NONE',
    context_tags = '[]',
    recommended_checks = '["현재 시장 데이터와 탐지 규칙을 다시 확인하세요."]',
    market_observed_at = anomaly.detected_at,
    caution = '이 신호만으로 불공정거래, 시세조종, 투자 위험 또는 투자 가치를 판단할 수 없습니다.',
    measurements = '[]'
FROM surveillance_case surveillance
WHERE surveillance.legacy_anomaly_id = anomaly.id;

INSERT INTO case_status_history (case_id, from_status, to_status, actor, detail, changed_at)
SELECT id, NULL, 'NEW', 'migration', '기존 anomaly를 단일 신호 사건으로 변환', updated_at
FROM surveillance_case;

ALTER TABLE anomaly_record
    ALTER COLUMN stock_name SET NOT NULL,
    ALTER COLUMN case_id SET NOT NULL,
    ALTER COLUMN title SET NOT NULL,
    ALTER COLUMN summary SET NOT NULL,
    ALTER COLUMN explanation SET NOT NULL,
    ALTER COLUMN direction SET NOT NULL,
    ALTER COLUMN context_tags SET NOT NULL,
    ALTER COLUMN recommended_checks SET NOT NULL,
    ALTER COLUMN caution SET NOT NULL,
    ALTER COLUMN measurements SET NOT NULL,
    ADD CONSTRAINT fk_anomaly_case FOREIGN KEY (case_id) REFERENCES surveillance_case(id),
    ADD CONSTRAINT chk_anomaly_direction CHECK (direction IN ('UP', 'DOWN', 'BUY', 'SELL', 'NONE')),
    ADD CONSTRAINT chk_anomaly_context_tags_json CHECK (jsonb_typeof(context_tags::jsonb) = 'array'),
    ADD CONSTRAINT chk_anomaly_checks_json CHECK (jsonb_typeof(recommended_checks::jsonb) = 'array'),
    ADD CONSTRAINT chk_anomaly_measurements_json CHECK (jsonb_typeof(measurements::jsonb) = 'array');

ALTER TABLE anomaly_record DROP CONSTRAINT chk_anomaly_rule_type;
ALTER TABLE anomaly_record ADD CONSTRAINT chk_anomaly_rule_type CHECK (
    rule_type IN (
        'PRICE_LIMIT', 'PRICE_SPIKE', 'VOLUME_SURGE', 'ORDERBOOK_IMBALANCE',
        'INVESTMENT_WARNING', 'PRICE_VOLUME_SURGE'
    )
);
CREATE INDEX idx_anomaly_case_time ON anomaly_record (case_id, detected_at);

ALTER TABLE surveillance_case DROP COLUMN legacy_anomaly_id;
